"""Aggregate Chunk-3 results into outputs/multi_room/dense/SUMMARY.md.

Reads:
  - outputs/multi_room/dense/scalars.json  (last val entry → per-train-room metrics)
  - outputs/multi_room/dense/train_meta.json (n_iters_actual, early_stop, wall)
  - outputs/multi_room/dense/zero_shot/L*/metrics.json (per-zero-shot-L)
  - outputs/multi_room/dense/latent_probe/latent_probe.json
Writes:
  - outputs/multi_room/dense/SUMMARY.md
  - outputs/multi_room/dense/lsd_vs_L.png  (train + zero-shot on same axes)
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

REPO_ROOT = Path(__file__).resolve().parent.parent


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=str(REPO_ROOT / "outputs/multi_room/dense"))
    args = ap.parse_args()
    root = Path(args.root)

    scalars_path = root / "scalars.json"
    train_meta_path = root / "train_meta.json"
    if not scalars_path.exists() or not train_meta_path.exists():
        raise FileNotFoundError(f"missing scalars.json or train_meta.json under {root}")
    scalars = json.loads(scalars_path.read_text())
    meta = json.loads(train_meta_path.read_text())
    val_rows = [r for r in scalars if r.get("phase") == "val"]
    if not val_rows:
        raise RuntimeError("no validation rows recorded")
    last_val = val_rows[-1]

    train_rooms = []
    for L in meta["L_list"]:
        train_rooms.append({
            "L": float(L),
            "lsd_db": last_val.get(f"L_{L}_lsd_db"),
            "complex_l1": last_val.get(f"L_{L}_complex_l1"),
            "magnitude_l1": last_val.get(f"L_{L}_magnitude_l1"),
            "phase_l1": last_val.get(f"L_{L}_phase_l1"),
        })
    train_rooms.sort(key=lambda r: r["L"])

    zero_shot_rooms = []
    for d in sorted((root / "zero_shot").glob("L*/")):
        m_path = d / "metrics.json"
        if m_path.exists():
            zero_shot_rooms.append(json.loads(m_path.read_text()))
    zero_shot_rooms.sort(key=lambda r: r["L"])

    probe = None
    pp = root / "latent_probe" / "latent_probe.json"
    if pp.exists():
        probe = json.loads(pp.read_text())

    md = ["# Chunk-3 dense-sweep multi-room — cross-room summary\n",
          "\nGenerated by `scripts/multi_room_summary.py`. One auto-decoder model trained "
          "on the 7 dense-sweep training rooms; zero-shot adaptation on 6 unseen L values.\n",
          "\n## Training metadata\n",
          f"- iters: {meta['n_iters_actual']} / {meta['n_iters_target']}  ",
          f"({'early-stopped' if meta['stopped_early'] else 'completed full'})\n",
          f"- wall-clock: {meta['wall_clock_seconds']/60:.1f} min  "
          f"({meta['wall_clock_seconds']/3600:.2f} h)\n"]
    if meta.get("stop_reason"):
        md.append(f"- stop_reason: {meta['stop_reason']}\n")
    md.append(f"- final val total weighted loss: {last_val.get('lsd_db'):.3f} dB (aggregated full-band LSD)\n")

    md.append("\n## Per-training-room reconstruction (final val)\n")
    md.append("| L (m) | LSD (dB) | complex L1 | magnitude L1 | phase L1 |\n"
              "|------:|---------:|-----------:|-------------:|---------:|\n")
    for r in train_rooms:
        md.append(f"| {r['L']:.2f} | {r['lsd_db']:.2f} | {r['complex_l1']:.4f} | "
                  f"{r['magnitude_l1']:.4f} | {r['phase_l1']:.3f} |\n")

    md.append("\n## Zero-shot adaptation at unseen L\n")
    md.append("| L (m) | obs LSD (dB) | held-out LSD (dB) | held-out complex L1 | "
              "modal MAE (Hz) | modal recall | n picked / n analytical |\n"
              "|------:|-------------:|------------------:|--------------------:|---------------:|"
              "-------------:|------------------------:|\n")
    for r in zero_shot_rooms:
        mr = r["held_out_modal_recall"]
        mr_str = f"{mr:.3f}" if mr is not None else "—"
        md.append(
            f"| {r['L']:.2f} | {r['obs_lsd_db']:.2f} | {r['held_out_lsd_db']:.2f} | "
            f"{r['held_out_complex_l1']:.4f} | {r['held_out_modal_mae_hz']:.2f} | "
            f"{mr_str} | {r['n_picked']} / {r['n_analytical']} |\n"
        )

    if probe:
        md.append("\n## Latent manifold probe (PCA)\n")
        md.append(f"- intrinsic_dim (95% variance): **{probe['intrinsic_dim_95pct']}**\n")
        md.append(f"- PC1 vs L linear-fit R²: **{probe['pc1_vs_L_r2']:.3f}**\n")
        md.append(f"- slope of PC1 vs L: {probe['slope_PC1_per_m']:.3f} per m\n")
        md.append(f"- per-PC explained variance: "
                  f"{[f'{v:.3f}' for v in probe['pca_explained_variance'][:6]]}\n")
        md.append("- See `latent_probe/figures/{latent_pca_1d, latent_pca_2d, latent_variance}.png`\n")

    md.append("\n## Cross-L LSD\n![lsd_vs_L](lsd_vs_L.png)\n")

    md.append("\n## Per-zero-shot-L artifacts\n")
    for r in zero_shot_rooms:
        rel = f"zero_shot/L{r['L']}/figures"
        md.append(f"- L={r['L']:.2f}: [overlay]({rel}/zero_shot_overlay.png), "
                  f"[modal_tracking]({rel}/zero_shot_modal_tracking.png), "
                  f"[receiver_grid]({rel}/zero_shot_receiver_grid.png), "
                  f"[adapt_loss]({rel}/adapt_loss_curve.png)\n")

    (root / "SUMMARY.md").write_text("".join(md))

    # Cross-L LSD plot.
    Ls_train = [r["L"] for r in train_rooms]
    lsd_train = [r["lsd_db"] for r in train_rooms]
    Ls_test = [r["L"] for r in zero_shot_rooms]
    lsd_test = [r["held_out_lsd_db"] for r in zero_shot_rooms]
    fig, ax = plt.subplots(figsize=(8, 4))
    ax.plot(Ls_train, lsd_train, "o-", color="steelblue", label="training rooms (val LSD)")
    if Ls_test:
        ax.plot(Ls_test, lsd_test, "^-", color="indianred",
                label="zero-shot held-out (LSD on 56 receivers)")
    ax.set_xlabel("L (m)"); ax.set_ylabel("full-band LSD (dB)")
    ax.set_title("Chunk-3 dense sweep: train (val) and zero-shot (held-out) LSD vs L")
    ax.grid(True, alpha=0.3); ax.legend()
    fig.tight_layout()
    fig.savefig(root / "lsd_vs_L.png", dpi=110, bbox_inches="tight")
    plt.close(fig)

    print(f"# wrote {root/'SUMMARY.md'} and {root/'lsd_vs_L.png'}")


if __name__ == "__main__":
    main()
