"""Aggregate per-room eval.json files into outputs/single_room/SUMMARY.md
and outputs/single_room/lsd_vs_L.png.

Run after `single_room_eval.sh` completes for every L. CPU-only, fast.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

REPO_ROOT = Path(__file__).resolve().parent.parent


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=str(REPO_ROOT / "outputs/single_room"))
    args = ap.parse_args()
    root = Path(args.root)

    rooms = []
    for d in sorted(root.glob("L*/")):
        ep = d / "eval.json"
        if ep.exists():
            with open(ep) as f:
                rooms.append(json.load(f))
    if not rooms:
        raise RuntimeError(f"no eval.json files under {root}")

    rooms.sort(key=lambda r: r["L"])

    md = ["# Single-room overfit baseline — cross-room summary\n",
          "\nGenerated by `scripts/single_room_summary.py`. One per-room model trained per L.\n",
          "\n## Per-room metrics\n",
          "| L (m) | ckpt iter | f_S (Hz) | modal MAE (Hz) | modal recall | full LSD (dB) | env LSD (dB) | complex L1 | mag L1 | phase L1 |\n",
          "|------:|---------:|---------:|---------------:|-------------:|--------------:|-------------:|-----------:|-------:|---------:|\n"]
    for r in rooms:
        m = r["modal"]
        fb = r["full_band"]
        md.append(
            f"| {r['L']:.2f} | {r['ckpt_iter']} | {r['f_schroeder_hz']:.0f} | "
            f"{m['mae_hz']:.2f} | {m['recall_at_tol']:.3f} | "
            f"{fb['lsd_db']:.2f} | {fb['envelope_lsd_db']:.2f} | "
            f"{fb['complex_l1']:.4f} | {fb['magnitude_l1']:.4f} | {fb['phase_l1']:.3f} |\n"
        )

    md.append("\n## ISM baseline (centre receiver picker recall)\n")
    md.append("For comparison, the ISM-vs-analytical recall at the centre receiver per room "
              "(from the noise-floor pipeline). Our model can't beat this — it's an upper bound.\n\n")
    md.append("| L (m) | ISM modal recall |\n|------:|-----------------:|\n")
    for r in rooms:
        md.append(f"| {r['L']:.2f} | {r['ism_modal_recall_at_centre']:.3f} |\n")

    md.append("\n## Per-band modal recall (predicted)\n")
    md.append("| L (m) | low (≤5) | mid (6–15) | high (16+) |\n|--:|---------:|-----------:|-----------:|\n")
    for r in rooms:
        bd = r["modal"]["per_band"]
        md.append(
            f"| {r['L']:.2f} | "
            f"{bd['low']['recall']:.2f} ({bd['low']['n_matched']}/{bd['low']['n_modes']}) | "
            f"{bd['mid']['recall']:.2f} ({bd['mid']['n_matched']}/{bd['mid']['n_modes']}) | "
            f"{bd['high']['recall']:.2f} ({bd['high']['n_matched']}/{bd['high']['n_modes']}) |\n"
        )

    md.append("\n## Per-room artifacts\n")
    for r in rooms:
        rel = f"L{r['L']}/figures"
        md.append(f"- L={r['L']:.2f}: [training_curves]({rel}/training_curves.png), "
                  f"[modal_tracking]({rel}/modal_tracking.png), "
                  f"[spectrum_overlay]({rel}/spectrum_overlay.png), "
                  f"[receiver_grid]({rel}/receiver_grid.png) — "
                  f"[eval.json](L{r['L']}/eval.json)\n")

    md.append("\n## Cross-room LSD vs L\n")
    md.append("![lsd_vs_L](lsd_vs_L.png)\n")

    (root / "SUMMARY.md").write_text("".join(md))

    Ls = np.array([r["L"] for r in rooms])
    lsd = np.array([r["full_band"]["lsd_db"] for r in rooms])
    env = np.array([r["full_band"]["envelope_lsd_db"] for r in rooms])
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.plot(Ls, lsd, "o-", color="indianred", label="full-band LSD (dB)")
    ax.plot(Ls, env, "s-", color="steelblue", label="envelope LSD (dB)")
    ax.set_xlabel("L (m)")
    ax.set_ylabel("LSD (dB)")
    ax.set_title("Single-room overfit: full-band & envelope LSD vs L")
    ax.grid(True, alpha=0.3)
    ax.legend()
    fig.tight_layout()
    fig.savefig(root / "lsd_vs_L.png", dpi=110, bbox_inches="tight")
    plt.close(fig)
    print(f"# wrote {root / 'SUMMARY.md'} and {root / 'lsd_vs_L.png'}")


if __name__ == "__main__":
    main()
